test3: test3.c
	gcc test3.c -o test3 -I /usr/local/include/SDL2/ -l SDL2-2.0.0

test2: test2.c
	gcc test2.c -o test2 -I /usr/local/include/SDL2/ -l SDL2-2.0.0

test: test.c
	gcc test.c -o test -I /usr/local/include/SDL2/ -l SDL2-2.0.0
