test_06: 06_extension_libraries_and_loading_other_image_formats.c
	gcc 06_extension_libraries_and_loading_other_image_formats.c -o test_06 -I /usr/local/include/SDL2/ -I /usr/local/include/SDL2 -l SDL2-2.0.0 -l SDL2_image
